image: ruby:3.3.6

pipelines:
  default:
    - step:
          name: Setup
          caches:
            - bundler
          script:
            - bundle config set path 'vendor/bundle'
            - bundle install
            - bundle binstubs --all
    - parallel:
      - step:
            name: Rubocop
            caches:
              - bundler
            script:
              - if [ "${BITBUCKET_PR_DESTINATION_BRANCH}" == "main" ]; then printf 'not a target branch we want to check'; exit; fi
              - bundle config set path 'vendor/bundle'
              - bundle install
              - bundle binstubs --all
              - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
              - git fetch
              - git diff-tree -r --no-commit-id --name-only origin/main $BITBUCKET_COMMIT | xargs ls -1 2>/dev/null | xargs bundle exec rubocop --debug --force-exclusion
    - parallel:
      - step:
          name: Test
          caches:
            - bundler
          services:
            - postgres
          script:
            - apt-get update && apt-get install -y nodejs
            - bundle config set path 'vendor/bundle'
            - export DB_HOST=127.0.0.1
            - export DB_USERNAME=test_user
            - export DB_PASSWORD=test_user_password!
            - bundle install
            - bundle binstubs --all
            - export RAILS_ENV=test
            - bundle exec rake db:create
            - bundle exec rake db:setup
            - bundle exec rake db:migrate
            - bundle exec rake db:test:prepare
            - bundle exec rspec
definitions:
  caches:
    bundler:
      key:
        files:
          - Gemfile.lock
          - "**/*.gemspec"
      path: vendor/bundle
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: lvam_test
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_user_password!
