# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: "<%= Rails.application.credentials.dig(:db, :username) %>"
  password: "<%= Rails.application.credentials.dig(:db, :password) %>"
  host: <%= Rails.application.credentials.dig(:db, :host) %>

development:
  primary: &primary_development
    <<: *default
    database: lvam_development
  cache:
    <<: *primary_development
    database: lvam_development_cache
  queue:
    <<: *primary_development
    database: lvam_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: lvam_development_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: lvam_rewrite_test

production:
  primary: &primary_production
    <<: *default
    database: lvam_production
  cache:
    <<: *primary_production
    database: lvam_production_cache
  queue:
    <<: *primary_production
    database: lvam_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: lvam_production_cable
    migrations_paths: db/cable_migrate

staging:
  primary: &primary_staging
    <<: *default
    database: lvam_staging
  cache:
    <<: *primary_staging
    database: lvam_staging_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_staging
    database: lvam_staging_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_staging
    database: lvam_staging_cable
    migrations_paths: db/cable_migrate
